Bag of Words in Natual Language Processing(NLP)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text': ['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df["text"])

In [8]:
# Our Vocabs
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]

In [10]:
cv.fit_transform(["campusx watch and write comment"]).toarray()

array([[1, 1, 1, 1, 1]])

N-Grams

N-Grams are the advanced version of Bag of Words

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [4]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2)) # ngram range tell us how many merged word we need in a word!